# Generated by Django 2.1 on 2018-08-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indate', models.DateField()),
                ('outdate', models.DateField()),
                ('indate_intime', models.DateTimeField(blank=True)),
                ('outdate_outtime', models.DateTimeField(blank=True)),
                ('shift', models.CharField(max_length=2)),
                ('divid', models.CharField(max_length=3)),
                ('secid', models.CharField(max_length=4)),
                ('wtype', models.CharField(max_length=4)),
                ('mastid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.Master')),
            ],
        ),
    ]
